# ========================================================================================================================================
#    _____                       _   _   _                             _____    _____
#   |  __ \                     | | | | (_)                    /\     |  __ \  |_   _|
#   | |  | |   ___    __ _    __| | | |  _   _ __     ___     /  \    | |__) |   | |
#   | |  | |  / _ \  / _` |  / _` | | | | | | '_ \   / _ \   / /\ \   |  ___/    | |
#   | |__| | |  __/ | (_| | | (_| | | | | | | | | | |  __/  / ____ \  | |       _| |_
#   |_____/   \___|  \__,_|  \__,_| |_| |_| |_| |_|  \___| /_/    \_\ |_|      |_____|
#
#               By Vengelis_
# ========================================================================================================================================

############################################################
# +------------------------------------------------------+ #
# |                       Notes                          | #
# +------------------------------------------------------+ #
############################################################

# Deadline Compatible 10.0
# Version 1.0.0 Alpha